spring:
  application:
    name: gc-board-refactoring-prod

  datasource:
    driver-class-name: ${MYSQL_DRIVER_NAME}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

oauth2:
  providers:
    google:
      login-url: ${GOOGLE_LOGIN_URL}
      token-url: ${GOOGLE_TOKEN_URL}
      user-info-url: ${GOOGLE_USERINFO_URL}
      client-id: ${GOOGLE_CLIENT_ID}
      redirect-url: ${GOOGLE_REDIRECT_URL}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      grant-type: ${GOOGLE_GRANT_TYPE}

web:
  front-end-url: ${FRONTEND_URL}